// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rk
List rk(NumericVector x, NumericVector y, NumericVector U, NumericVector V, IntegerVector m, IntegerVector n, NumericVector t_step);
RcppExport SEXP _currently_rk(SEXP xSEXP, SEXP ySEXP, SEXP USEXP, SEXP VSEXP, SEXP mSEXP, SEXP nSEXP, SEXP t_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type U(USEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t_step(t_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(rk(x, y, U, V, m, n, t_step));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_currently_rk", (DL_FUNC) &_currently_rk, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_currently(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
